apiVersion: v1
kind: Pod
metadata:
	name: nginx
spec:
	containers:
		- name: nginx
		  image: nginx:1.19.10
		  ports:
		  - containerPort: 3000
		- name: redis
		  image: nginx:6.2.2
		  ports:
		  - containerPort: 3001
			
