apiVersion: apps/v1
kind: Deployment
metadata:
	name: myfirstdeploy
	labels:
		app: myfirst-app
spec:
	replicas: 2
	selector:
		matchLabels:
			app: myfirst-app
	template:
		metadata:
			labels:
				app: myfirst-app
  containers:
  -	name: nginx
    image: nginx:1.19.10
    ports:
    -	containerPort: 80
