
apiVersion: v1
kind: Pod
metadata: 
	name: redis
spec:
	volumes:
    -	name: redis-storage
      persistentVolumeClaim:
		    claimName: redis-pvc
 	containers:
  -	name:  redispv-container
    image: redis:6.2.2
    ports:
      -	containerPort: 80
        name: redis
	  volumeMounts:
      -	mountPath: "/data"
        name: redis-storage









